- hosts: cloud-vps
  become: true
  vars_files:
    - ../../vars/common-vars.yaml

  tasks:

    - name: Update all packages to the latest version
      apt:
        upgrade: full

    - name: Install podman
      apt:
        name: podman
        state: latest
        update_cache: true

