- hosts: "{{ target_hosts | default('cloud-vps-node01') }}"
  become: true
  vars_files:
    - ../vars/common-vars.yaml

  tasks:

    - name: Update all packages to the latest version
      apt:
        upgrade: full

    #install sshfs
    - name: Install sshfs package
      ansible.builtin.package:
        name: sshfs
        state: present
        update_cache: true

    #ensure SSH connection to control-plane

    #sshfs - mount folder from control-plane

    #connect to control-plane - add node
