- hosts: "{{ target_hosts | default('cloud-vps-node01') }}"
  become: true
  vars_files:
    - ../vars/common-vars.yaml
    #- ../../../salaserver/vars/common_vars.yaml

  tasks:

    - name: Update all packages to the latest version
      apt:
        upgrade: full

    #install sshfs
    - name: Install sshfs package
      ansible.builtin.package:
        name: sshfs
        state: present
        update_cache: true

    # - name: Add hostname to /etc/hosts - controlplane
    #   lineinfile:
    #     path: /etc/hosts
    #     state: present
    #     regexp: '^{{ controlplane_hostname }}'
    #     line: '{{ controlplane_ip }} {{ controlplane_hostname }}'
    #
    # - name: Run whoami command
    #   ansible.builtin.command: whoami
    #     register: login_user

    - name: Display the result
      ansible.builtin.debug:
        msg: "The current user is: {{ ansible_user }}"

    - name: Ensure the .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: '0700'

    # - name: Generate an OpenSSH keypair
    #   community.crypto.openssh_keypair:
    #     path: "/home/{{ ansible_user }}/.ssh/id_w01_rsa"
    #     type: rsa
    #     size: 4096
    #     state: present
    #     force: no  # Set to 'yes' if you want to overwrite existing keys

    - name: Copy SSH private key to remote server
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa_node
        dest: "/home/{{ ansible_user }}/.ssh" # Path on the remote server
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'


    - name: Copy SSH public key to remote server
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa_node.pub
        dest: "/home/{{ ansible_user }}/.ssh" # Path on the remote server
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0640'

    # - name: "Optional: Automatically 're-learn' the new key for ansible (Non-interactive)"
    #   # This prevents the "Are you sure you want to connect?" prompt later
    #   ansible.builtin.shell: "ssh-keyscan -H k8smaster >> /home/ansible/.ssh/known_hosts"
    #   register: keyscan_result
    #   changed_when: "keyscan_result.rc == 0"
    #
    # - name: "Optional: Automatically 're-learn' the new key for root (Non-interactive)"
    #   # This prevents the "Are you sure you want to connect?" prompt later
    #   ansible.builtin.shell: "ssh-keyscan -H k8smaster >> /root/.ssh/known_hosts"
    #   register: keyscan_result
    #   changed_when: "keyscan_result.rc == 0"
    #
    # - name: Set /etc/fuse.conf -
    #   ansible.builtin.lineinfile:
    #     path: /etc/fuse.conf
    #     state: present
    #     regexp: '^user_allow_other'
    #     line: 'user_allow_other'
    #
    # - name: Mount remote filesystem via SSHFS
    #   ansible.posix.mount:
    #     path: /srv/virtiofs
    #     src: ansible@k8smaster:/srv/virtiofs
    #     fstype: fuse.sshfs
    #     opts: "_netdev,x-systemd.automount,x-systemd.idle-timeout=60,IdentityFile=/home/ansible/.ssh/id_rsa_node,allow_other,reconnect,ServerAliveInterval=15"
    #     state: mounted
    #
    # #connect to control-plane - add node

