---
- hosts: cloud-vps
  become: true
  vars_files:
    - ./vars/common-vars.yaml

  tasks:

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Keyrings - Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Keyrings - Download the ASCII-armored GPG key file
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: "/etc/apt/keyrings/docker.asc"
        mode: '0644'

    - name: Keyrings - Add the APT repository using the binary GPG key
      ansible.builtin.apt_repository:
        repo: "{{ docker_repoline }}"
        state: present
        filename: "docker"
        update_cache: yes


    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Add user ansible/feri to docker group
      user:
        name: "{{ item }}"
        state: present
        groups: docker
        append: true
      with_items:
        - "{{ server_username }}"
        - "{{ ansible_username }}"

    - block:

        - name: Clone docker repo from github
          git:
            repo: 'https://github.com/fsklenar/docker.git'
            dest: /srv/data/docker
            clone: yes
            update: no

        - name: Set owner to repo
          ansible.builtin.file:
            path: /srv/data/docker
            owner: "{{ server_username }}"
            group: "{{ server_username }}"
            recurse: true
            mode: o-rwx

        - name: Run all docker containers after "@reboot"
          cron:
            name: "Run all dockers after reboot"
            special_time: reboot
            job: "/srv/data/docker/runall.sh"
        #
        # - name: Run sync of Foto backup into Immich application after "@reboot"
        #   cron:
        #     name: "Run sync of Foto backup into Immich application after reboot"
        #     special_time: reboot
        #     job: "/srv/data/docker/Immich/run-sync.sh"

        - name: Update apt and install docker-compose
          apt:
           pkg:
             - docker-compose
             - docker-compose-plugin
           state: latest
           update_cache: true

      when: "'docker-vm' in group_names"

