- hosts: cloud-vps-haproxy
  become: true
  vars_files:
    - ./vars/common-vars.yaml
  vars_prompt:
    - name: "manual_password"
      prompt: "Enter password for {{ salauser_username }}"
      private: yes # Hides your typing

  tasks:

    - name: Update all packages to the latest version
      apt:
        upgrade: full

    - name: Install HAProxy
      apt:
        name: haproxy
        state: latest
        update_cache: true
    #
    # - name: Install python3-passlib
    #   apt:
    #     name: python3-passlib
    #     state: latest
    #     update_cache: true


    - name: Copy haproxy.cfg to server
      copy:
        src: vars/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start HAProxy service
      ansible.builtin.systemd_service:
        name: "haproxy.service"
        enabled: true
        state: reloaded
        daemon_reload: true

    - name: "Update user password for {{ server_username }}"
      ansible.builtin.user:
        name: "{{ server_username }}"
        password: "{{ manual_password | ansible.builtin.password_hash('sha512') }}"


