---
- hosts: salaserver
  become: true
  vars:
    my_pass: "{{ lookup('password', '/tmp/passwordfile length=15 chars=ascii_letters') }}"
  vars_files:
    - ../vars/common_vars.yaml

  tasks:
    - name: Update apt and install required KVM packages
      apt:
        pkg:
          - qemu-kvm 
          - virtinst 
          - libvirt-clients 
          - bridge-utils 
          - libvirt-daemon-system
          - guestfs-tools
          - virtiofsd
        state: latest
        update_cache: true

    - name: Copy shutdown script
      copy:
        src: vars/shut.sh
        dest: /usr/local/bin/shut
        mode: '0750'
        group: root
        owner: "{{ server_username }}"

    - name: create /srv/data folder
      file:
        path: /srv/data
        state: directory
        mode: '0750'
        owner: "{{ server_username }}"
        group: "libvirt-qemu"

    - name: create /srv/data/iso folder
      file:
        path: /srv/data/iso
        state: directory
        mode: '0770'
        owner: "{{ server_username }}"
        group: "{{ ansible_username }}"

    - name: create /srv/data/img folder
      file:
        path: /srv/data/img
        state: directory
        mode: '0770'
        owner: "{{ server_username }}"
        group: "libvirt-qemu"

    - name: create /srv/data/virtiofs folder for sharing into VMs as Persistent Volume - prometheus
      file:
        path: /srv/data/virtiofs/prometheus
        state: directory
        mode: '0777'
        owner: "libvirt-qemu"
        group: "{{ server_username }}"

    - name: create /srv/data/virtiofs folder for sharing into VMs as Persistent Volume - grafana
      file:
        path: /srv/data/virtiofs/grafana
        state: directory
        mode: '0777'
        owner: "libvirt-qemu"
        group: "{{ server_username }}"

    - name: create /srv/data/virtiofs folder for sharing into VMs as Persistent Volume - wordpress
      file:
        path: /srv/data/virtiofs/wordpress
        state: directory
        mode: '0777'
        owner: "libvirt-qemu"
        group: "{{ server_username }}"

    - name: create /srv/data/virtiofs folder for sharing into VMs as Persistent Volume - mysql
      file:
        path: /srv/data/virtiofs/mysql
        state: directory
        mode: '0777'
        owner: "libvirt-qemu"
        group: "{{ server_username }}"

    - name: check if netplan bridge file exists
      stat:
        path: "/etc/netplan/01-bridge.yaml"
      register: bridge_file_status

    - block:
    
        - name: create bridge network
          copy:
            src: vars/01-bridge.yaml
            dest: /etc/netplan/
            mode: '0600'
            group: root
            owner: root 

        - name: check if netplan bridge file exists v2
          stat:
            path: "/etc/netplan/01-bridge.yaml"
          register: bridge_file_v2_status
          
        - name: delete common network yaml file
          file:
            path: /etc/netplan/50-cloud-init.yaml
            state: absent 
          when: bridge_file_v2_status.stat.exists	        

        - name: netplan apply
          shell: |
            sudo netplan apply
            sleep 30

      when: not bridge_file_status.stat.exists

      
    - name: copy bridger xml file
      copy: 
        src: vars/02-kvm-bridger-network.yaml 
        dest: /tmp/
        mode: '0600'
        group: root
        owner: root
      
    - name: create bridger network for KVM
      shell: |
        sudo virsh net-define /tmp/02-kvm-bridger-network.yaml
        sudo virsh net-start bridged-network
        sudo virsh net-autostart bridged-network 
      
