---
- hosts: salaserver
  become: true
  vars:
    my_pass: "{{ lookup('password', '/tmp/passwordfile length=15 chars=ascii_letters') }}"
  vars_files:
    - ../vars/common_vars.yaml

  tasks:    
  
    - name: check if img file exists
      stat:
        path: "/srv/data/img/{{ vm_img_name }}"
      register: ubuntu_file_status
      
    - block:

      - name: download ubuntu image, if not exists
        get_url:
          url: "{{ ubuntu_img_url }}"
          dest: /srv/data/img/{{ vm_img_name }}
          mode: '0750'
          owner: "libvirt-qemu"
          group: "{{ server_username }}"

      - name: copy netplan network file with static IP
        copy: 
          src: vm/01-vm-netplan-network.yaml 
          dest: /tmp/01-vm-netplan-network.yaml
          mode: '0600'
          group: root
          owner: root

      - name: Set coorect IP to netplan network
        lineinfile:
          path: /tmp/01-vm-netplan-network.yaml
          state: present
          regexp: '^                - <vm-ip>/24'
          line: '                - {{ vm_ip }}/24'

      - name: copy ssh public key
        copy: 
          src: ~/.ssh/id_rsa.pub 
          dest: /tmp/id_rsa.pub
          mode: '0600'
          group: root
          owner: root
           
      - set_fact:
          root_pass: "{{ my_pass }}"
          
      - name: showing new root password
        debug:
          msg: "{{ root_pass }}"
        
      - name: write random password to tempfile
        copy: content="{{ root_pass }}" dest=/tmp/passwordfile
        
      - name: set random root password to image, netplan network configuration 
        shell: |
           randpass=`cat /tmp/passwordfile`
           sudo qemu-img resize "/srv/data/img/{{ vm_img_name }}" +20G
           sudo virt-customize -a "/srv/data/img/{{ vm_img_name }}" --root-password password:$randpass \
             --upload /tmp/01-vm-netplan-network.yaml:/etc/netplan/01-vm-netplan-network.yaml \
             --ssh-inject root:file:/tmp/id_rsa.pub \
             --timezone "Europe/Bratislava" \
             --uninstall openssh-server \
             --firstboot-install openssh-server \
             --firstboot-command "growpart /dev/vda 1" \
             --firstboot-command "resize2fs /dev/vda1" \
             --hostname "{{ vm_hostname }}"
           rm /tmp/passwordfile

      when: not ubuntu_file_status.stat.exists
