---
- hosts: all
  become: true
  vars:
    my_pass: "{{ lookup('password', '/tmp/passwordfile length=15 chars=ascii_letters') }}"
  vars_files:
    - vars/common_vars.yaml

  tasks:    
  
    - name: check if img file exists
      stat:
        path: "/srv/data/img/ubuntu-01.img"
      register: ubuntu_file_status
      
    - name: Mitigations off
      lineinfile:
        path: /etc/default/grub
        state: present
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="mitigations=off"'
          
    - block: 

      - name: download ubuntu image, if not exists
        get_url:
          url: "{{ ubuntu_img_url }}"
          dest: /srv/data/img/ubuntu-01.img
          mode: '0750'
          owner: "libvirt-qemu"
          group: "{{ server_username }}"

      - name: copy netplan network file with static IP
        copy: 
          src: vm/01-netplan-network.yaml 
          dest: /tmp/01-netplan-network.yaml
          mode: '0600'
          group: root
          owner: root
           
      - set_fact:
          root_pass: "{{ my_pass }}"
          
      - name: showing new root password
        debug:
          msg: "{{ root_pass }}"
        
      - name: write random password to tempfile
        copy: content="{{ root_pass }}" dest=/tmp/passwordfile
        
      - name: set random root password to image, netplan network configuration 
        shell: |
           randpass=`cat /tmp/passwordfile`
           sudo virt-customize -a "/srv/data/img/ubuntu-01.img" --root-password password:$randpass --upload /tmp/01-netplan-network.yaml:/etc/netplan/01-netplan-network.yaml
           rm /tmp/passwordfile

      when: not ubuntu_file_status.stat.exists
