---
- hosts: k8smaster
  become: true
  vars_files:
    - vars/common_vars.yaml

  tasks:    
          
    #- name: resize the disk /dev/vda1
        #shell: |
          #sudo growpart /dev/vda 1
          #sudo resize2fs /dev/vda1

    
