- hosts: cloud-vps-haproxy
  become: true
  vars_files:
    - ../vars/common-vars.yaml
  vars_prompt:
    - name: "manual_password"
      prompt: "Enter password for {{ server_username }}"
      private: yes # Hides your typing

  tasks:

    - name: "Update user password for {{ server_username }}"
      ansible.builtin.user:
        name: "{{ server_username }}"
        password: "{{ manual_password | ansible.builtin.password_hash('sha512') }}"


